coverage:
  precision: 0
  round: down
  range: "80...100"


ignore:
  - "ccf/manage.py"
  - "ccf/app/urls.py"
  - "ccf/app/wsgi.py"
  - "ccf/app/__init__.py"
  - "ccf/app/settings/prod.py"
  - "ccf/Docker Test Algorithm/invert.py"
