sudo: required

language: python
python: '3.6'
services:
- docker

before_install:
# Install heroku CLI
- wget -q0- https://toolbelt.heroku.com/install.sh | sh
# login to docker reqestries (dockerhub + heroku)
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- echo "$HEROKU_PASSWORD" | docker login -u "_" --password-stdin registry.heroku.com

install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

script:
- pytest app --cov=app
- black app --check --exclude=secret_key.py
- isort -rc --check .
- docker build -t ross3834/seng371p2 .
- docker tag ross3834/seng371p2 registry.heroku.com/$HEROKU_APP_NAME/web

after_success:
- codecov

deploy:
  provider: script
  script:
  # Push to dockerhub
   docker push ross3834/seng371p2;
   docker push registry.heroku.com/$HEROKU_APP_NAME/web;
   heroku container:push web --app $HEROKU_APP_NAME;
   heroku container:release web --app $HEROKU_APP_NAME
  branch: master
