language: python

python: "3.6"

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

script:
    - pytest --cov=app
    - black app --check
    - isort -rc --check .

after_success:
    - codecov


